# Generated by Django 4.1 on 2023-03-08 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="liked_by",
            field=models.ManyToManyField(related_name="liking", to=settings.AUTH_USER_MODEL),
        ),
    ]
