# Generated by Django 4.1 on 2023-02-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0003_tweet_liked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="liked_by",
        ),
    ]
